# Generated by Django 2.2.7 on 2019-11-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191121_1534'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre_prefer',
            field=models.ManyToManyField(related_name='prefer_users', to='movies.Genre'),
        ),
    ]
