# Generated by Django 2.2.7 on 2019-11-26 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0, '올바른 나이를 입력해주세요.'), django.core.validators.MaxValueValidator(200, '올바른 나이를 입력해주세요.')]),
            preserve_default=False,
        ),
    ]
