# Generated by Django 2.2.7 on 2019-11-26 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched_user',
            field=models.ManyToManyField(related_name='watched_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
